import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Provider, useSelector } from 'react-redux';
import { store } from '../redux/store';
import jobsData from "./data.json";
import Job from '../components/Job';
import { selectSomeFeature } from "../redux/features/someSlice"
import Filters from '../components/Filters';



export default function Home() {


	
	return (
		<Provider store = {store}>
			<div>  
				<Head>
					<title>Create Next App</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
					<link rel="preconnect" href="https://fonts.googleapis.com"/>
					<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin= "true"/>
					<link href="https://fonts.googleapis.com/css2?family=Spartan&display=swap" rel="stylesheet"/>
				</Head>
				<div className = {styles.headerDiv}>
					{/* hello */}
					<Image src = "/images/bg-header-desktop.svg" alt = "headerImage" layout = "fill" objectFit = "fill" priority = "true"/>
					
					
				</div>
				<div className={styles.jobs}>
				<Filters />

					{
						jobsData.map((job) => (
							<Job 
								key = {job.id}
								company = {job.company}
								logo = {job.logo}
								newFlag = {job.new}
								featured = {job.featured}
								position = {job.position}
								role = {job.role}
								level = {job.level}
								postedAt = {job.postedAt}
								contract = {job.contract}
								location = {job.location}
								languages = {job.languages}
								tools = {job.tools}
							/>
						))
					}
				</div>
				
			</div>
		</Provider>
		
	)
}


// export async function getStaticProps(){
// 	const res = await fetch("data.json");
// 	const data = await res.json();

// 	return {
// 		props: {
// 			data,
// 		},
// 	}
// }
